config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :events

  resources :attendances

  devise_for :users
  resources :contacts

  resources :groups

  resources :children do
    collection { post :import }
  end

  root 'children#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :children

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all.order(:id)

    respond_to do |format|
      format.html
      format.pdf do
        pdf = GroupsPdf.new(@groups, view_context)
        send_data pdf.render, filename: "groups_#{Time.now}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @children = @group.children.order(:last_name)
    # @children = Child.all.order(:last_name)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = GroupPdf.new(@children, @group, view_context)
        send_data pdf.render, filename: "group_#{Time.now}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :color)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_links
    @groups = Group.all.order(:id)
    @menu = []
    @groups.each do |group|
      @menu << group
    end
    @menu
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <!--<%= f.error_notification %>-->

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :color %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="right">
  <%= link_to 'Download Groups Pdf', format: :pdf %>
</div>
<h1>Listing Groups</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Count</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @groups.each do |group| %>
      <tr>
        <td style="color: #<%= group.color %>"><%= group.name %></td>
        <td style="color: #<%= group.color %>"><%= group.color %></td>
        <td>
          <span class="label round">
          <%= group.children.count %>
              </span>
        </td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<% @group.children.group(:gender).count.each do |key, val| %>
    <span class="info label right">
    <%= key %>
      <%= val %>
    </span>
<% end %>
<br>

<div class="right">
<%= link_to 'Download Pdf', format: :pdf %>
</div>
<h1 style="color: #<%= @group.color %>">
  <!--<strong>Name:</strong>-->
  <%= @group.name %>
</h1>




<p>
  <% @children.each do |child| %>
    <p>
      <%= child.last_name %>,
      <%= child.first_name %>
      <%= link_to "show", child %> | <%= link_to "edit", edit_child_path(child) %>
    </p>
  <% end %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>