config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :events

  resources :attendances

  devise_for :users
  resources :contacts

  resources :groups

  resources :children do
    collection { post :import }
  end

  root 'children#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order(:start)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start, :end, :price, :groups, :notes)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def countdown(t)
    time = distance_of_time_in_words_to_now(t)
    time
  end
  def duration(event)
    time = distance_of_time_in_words(event.start, event.end)
    time
  end
  def next_event
    ticker = ""
    @events = Event.order(:start)

    i = -1;
    @events.each_with_index { |event, index|
    if event.start > Time.now && i == -1
      puts i
      i = index
      puts i
      ticker += "Next Event: #{event.name} | #{event.groups} -- #{countdown(event.start)}"
    end

      }
    # end
    ticker
  end
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <fieldset>
      <legend>Start Datetime</legend>
      <%= f.input :start, label: false %>
    </fieldset>
    <fieldset>
      <legend>End Datetime</legend>
      <%= f.input :end, label: false %>
    </fieldset>
    <%= f.input :price %>
    <%= f.input :groups %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= link_to 'New Event', new_event_path, class: "right" %>
<h1>Listing Events</h1>



<div class="row" data-equalizer>
  <% @events.each do |event| %>

      <div class="medium-4 large-3 columns" data-equalizer-watch>

        <div class="panel">
          <h4>
            <small class="right">
              <%= event.start.to_formatted_s(:long) %>
            </small>
            <br>
            <small class="right">
              <%= duration(event) %>
            </small>
          </h4>
          <h3>
            <small>
              <%= event.name %>
            </small>
          </h3>

          <!--<br>-->
          <!--<br>-->
          <div class="row">
            <h3 class="right">
              <small>
                <%= number_to_currency(event.price) %>
              </small>
            </h3>
          </div>

          <p>
            <%= event.groups %>
          </p>

          <p>
            <%= event.notes %>
          </p>
          <br>
          <%= link_to 'Show', event, class: "button expand" %>
        </div>
      </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Groups:</strong>
  <%= @event.groups %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @event.notes %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>