config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :events

  resources :attendances

  devise_for :users
  resources :contacts

  resources :groups

  resources :children do
    collection { post :import }
  end

  root 'children#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_and_belongs_to_many :children
  has_many :attendances


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @q = Contact.ransack(params[:q])
    @contacts = @q.result.includes(:children)

    # @contacts = Contact.all
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"user-list.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
      format.pdf do
        pdf = ChildrenPdf.new(@children, view_context)
        send_data pdf.render, filename: "children_#{Time.now}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone, :email, :emergency_contact, :child_ids => [])
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def child_check(contact, tag, class_options = '')
    size = contact.children.size
    response = "<#{tag} "
    if size == 0
      response += "class='alert label round #{class_options}'>#{size}</#{tag}>"

    elsif size == 1
      response += "class='warning label round #{class_options}'>#{size}</#{tag}>"

    else
      response += "class='label round #{class_options}'>#{size}</#{tag}>"
    end
    response
  end
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>

    <!--<div class="form-inputs">-->
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :emergency_contact %>
    <%= f.input :phone %>
    <%= f.input :email %>

    <ul class="accordion small-11 columns" data-accordion>
      <li class="accordion-navigation">
        <a href="#children">Children</a>

        <div id="children" class="content">
          <%= f.association :children, as: :check_boxes, collection: Child.all.order(:last_name).to_a, label: false, :label_method => lambda { |child| "#{child.last_name}, #{child.first_name}" } %>
        </div>
      </li>
    </ul>
    <br>

    <!--</div>-->

    <div class="form-actions">
      <br>
      <%= f.button :submit %>
    </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<% if administrator %>
    <% if warning_facet(Contact).any? %>
        <div data-alert class="alert-box alert">
          <% warning_facet(Contact).each do |contact| %>

              No children found:
              <%= link_to("#{contact[:last_name]}, #{contact[:first_name]}", contact_path(contact[:link]), :class => "alert-link") %>
              <br>
          <% end %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
<% end %>

<% if administrator %>
    <% if duplicate_check(Contact).any? %>
        <div data-alert class="alert-box warning">
          <% duplicate_check(Contact).each do |contact| %>
              Duplicate found:
              <%= link_to("#{contact.last_name}, #{contact.first_name}", contacts_path(q: {last_name_eq: "#{contact.last_name}", first_name_eq: "#{contact.first_name}"}), :class => "alert-link") %>
              <br>
          <% end %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
<% end %>

<a href="#" data-reveal-id="searchModal">Search</a>
<div id="searchModal" class="reveal-modal" data-reveal aria-labelledby="Search" aria-hidden="true" role="dialog">
  <h3>
    <small class="right">
      Search
    </small>
  </h3>
  <div class="row">
    <%= search_form_for @q do |f| %>
        <!--&lt;!&ndash;= f.label :last_name_or_first_name_cont %>-->
        <div class="row collapse">
          <div class="small-10 columns">
            <%= f.search_field :last_name_or_first_name_cont, :placeholder => "Search first or last name" %>
          </div>
          <div class="small-2 columns">
            <%= f.button :class => "button postfix" do %>
                <div class="fa fa-search fa-lg"></div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>
<h1>Listing Contacts</h1>

<table class="show-for-medium-up">
  <thead>
  <tr>

    <th><%= sort_link @q, :first_name, "First Name" %></th>
    <th><%= sort_link @q, :last_name, "Last Name" %></th>
    <th><%= sort_link @q, :phone, "Phone" %></th>
    <th><%= sort_link @q, :email, "Email" %></th>
    <th>Children</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @contacts.each do |contact| %>

      <tr>

        <td><%= contact.first_name.titleize %></td>
        <td><%= contact.last_name.titleize %></td>
        <td>
          <a href="tel:<%= number_to_phone(contact.phone) %>" class="right">
            <%= number_to_phone(contact.phone) %>
          </a>
        </td>
        <td><%= contact.email %></td>
        <!--<td>-->
        <!--<span class="label round right">-->
        <%= simple_format(child_check(contact, "td")) %>
        <!--</span>-->
        <!--</td>-->
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<div class="show-for-small-only">
  <!--<div class="small-11 small-centered columns">-->
  <div><%= sort_link @q, :first_name, "First Name" %> |
    <%= sort_link @q, :last_name, "Last Name" %></div>
  <br>
  <% @contacts.each do |contact| %>

      <div class="panel">
        <!--<span class="label round right">-->
        <!--<%= contact.children.count %>-->
        <!--</span>-->
        <%= simple_format(child_check(contact, "span", "right")) %>
        <p class="fn"><%= "#{contact.last_name.titleize}, #{contact.first_name.titleize}" %></p>

        <p class="email">
          <%= contact.email %>
        </p>

        <p class="phone"><a href="tel:<%= number_to_phone(contact.phone) %>" class="right">
          <%= number_to_phone(contact.phone) %>
        </a>
        </p>

        <br>
        <td><%= link_to 'Show', contact %></td>
        |
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        |
        <td><%= link_to 'Delete', contact, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </div>
      <!--</div>-->
  <% end %>
</div>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <% if @contact.emergency_contact == true %>
      <strong>Emergency Contact</strong>
  <% end %>
</p>
<p>
  <strong>First name:</strong>
  <%= @contact.first_name.titleize %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name.titleize %>
</p>


<p>
  <strong>Phone:</strong>
  <a href="tel:<%= number_to_phone(@contact.phone) %>">
    <%= number_to_phone(@contact.phone) %>
  </a>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Children:</strong>
</p>
<% @contact.children.each do |child| %>
<p>
  <%= child.last_name %>,
  <%= child.first_name %>
  <%= link_to "show", child %> |
  <%= link_to "edit", edit_child_path(child) %>
</p>
      <!--<br>-->
<% end %>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>