config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :events

  resources :attendances

  devise_for :users
  resources :contacts

  resources :groups

  resources :children do
    collection { post :import }
  end

  root 'children#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
          <%= content_tag :div, msg %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="tab-bar">
  <section class="left-small">
    <a class="left-off-canvas-toggle menu-icon" href="#">
      <span></span>
    </a>
  </section>
  <section class="middle tab-bar-section">
    <h1 class="title">MMMC</h1>
  </section>
</nav>
<aside class="left-off-canvas-menu">
  <ul class="off-canvas-list">
    <li><label>Groups</label></li>
    <li class="has-submenu">

      <a href="#">Groups</a>
      <ul class="left-submenu">
        <li class="back"><a href="#">Back</a></li>
        <li>
          <%= link_to "Show All Groups", groups_path %>
        </li>
        <li>
          <%= link_to "New Group", new_group_path %>
        </li>
        <li><label>Groups</label></li>
        <% group_links.each do |link| %>
            <%= link_to link.name, group_path(link) %>
        <% end %>
      </ul>
    </li>
    <li><label>Kiddos infos</label></li>
    <li>
      <%= link_to "Children", children_path %>
    </li>
    <li>
      <%= link_to "New Child", new_child_path %>
    </li>
    <li><label>Contacts</label></li>
    <li>
      <%= link_to "Contacts", contacts_path %>
    </li>
    <li>
      <%= link_to "New Contact", new_contact_path %>
    </li>
    <li>
      <label>Events</label>
    </li>
    <li>
      <%= link_to "Show Events", events_path %>
    </li>
    <li>
      <label>User</label>
    </li>

    <% if user_signed_in? %>
        <li>
          <%= link_to(destroy_user_session_path, :method => :delete) do %>
              Log Out
          <% end %>
        </li>
        <li>
          <%= link_to(edit_user_registration_path(user_session)) do %>
              Edit User
          <% end %>
        </li>
        <% if administrator %>
            <li>
              <%= link_to admin_root_path do %>
                  Admin
              <% end %>
            </li>
        <% end %>
    <% else %>
        <li>
          <%= link_to new_user_session_path do %>
              Log In
          <% end %>
        </li>

    <% end %>
    <!--<li>-->
    <!--<%= link_to "Attendance", new_attendance_path %>-->
    <!--</li>-->
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? web_title(yield(:title)) : "MMMC Youth Program" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#2d89ef">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <meta name="theme-color" content="#ffffff">
</head>

<body>
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <%= render 'layouts/navigation' %>
    <div data-alert class="alert-box info">
      <%= next_event %>
      <!--<a href="#" class="close">&times;</a>-->
    </div>
    <section class="main-section">
      <div class="small-11 small-centered columns">
        <br>
        <%= render 'layouts/messages' %>
        <%= yield %>

      </div>
    </section>
    <div class="foot-space">
      <footer>
        <h4>
          <small>
            &copy; <%= copyright_notice_year_range(2015) %> <%= link_to "AW Technical Solutions", "http://www.awts.io/" %>  All Rights
            Reserved.
          </small>
        </h4>
      </footer>
    </div>
    <a class="exit-off-canvas"></a>
  </div>


</div>


</body>
</html>